Repository rabisnaqvi/Astral.js, pull requests merged in 2023-05, with the labels that each got.

#19 Updated the getState
  src/context.js
Labels: enhancement, good first issue

#21 14 update getstate to return an array which could be extracted like react usestate
  dist/astral.min.js
  dist/astral.min.js.map
  specs/context.spec.js
  src/context.js
Labels: enhancement, good first issue

#26 Fix broken hyperlink in the Getting Started section
  readme.md
Labels: documentation

#27 📃 #25 fix the code concepts link
  readme.md
Labels: documentation

#29 🌀Integrate Typescript or babel#15
  .babelrc
  .eslintrc.json
  babel.config.js
  dist/astral.min.js
  dist/astral.min.js.map
  jest.config.js
  jsdoc.json
  package-lock.json
  package.json
  specs/context.spec.js
  specs/event.spec.js
  specs/layout.spec.js
  src/context.js
  src/context.ts
  src/event.ts
  src/index.js
  src/index.ts
  src/layout.ts
  tsconfig.json
  typedoc.json
  webpack.conf.js
  yarn.lock
Labels: enhancement

#30 📃Break features and definitions into different lines in readme. #24
  readme.md
Labels: documentation

#31 🐲 Release 1.2.0
  .babelrc
  .eslintrc.json
  .github/workflows/main.yml
  CONTRIBUTING.md
  babel.config.js
  dist/astral.min.js
  dist/astral.min.js.map
  jest.config.js
  jsdoc.json
  package-lock.json
  package.json
  readme.md
  specs/context.spec.js
  specs/event.spec.js
  specs/layout.spec.js
  src/context.js
  src/context.ts
  src/event.ts
  src/index.js
  src/index.ts
  src/layout.ts
  tsconfig.json
  typedoc.json
  webpack.conf.js
  yarn.lock
Labels: status: awaiting release
